server:
  port: 8080
  shutdown: graceful

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
api:
  busan:
    base-url: http://apis.data.go.kr/6260000/
  seoul:
    base-url: http://openAPI.seoul.go.kr:8088/
